### ISSUE TITLE
EmployeePromotionSubDomain

### ISSUE THREAD

**Issue by tmusthofa** [manizer/slpayroll-subdomains#5]
Belum ada masa berlaku SK
belum ada tunjangan Masa Kerja

**Comment by tmusthofa** [comment]
Class Dropdown untuk grade dan basic salary belum ada

**Comment by chfern** [comment]
Check  
cdd6f94e18fcf1fb4a7ccb5b93c068c693610d1c
7ed1098c04b7478be2692dae314ef7a20fbfc15a
015d83d4b52210e109cb71aeda9fcf988c129a85
