### ISSUE TITLE
EmployeeSubDomain

### ISSUE THREAD

**Issue by tmusthofa** [manizer/slpayroll-subdomains#6]
- EmployeeEntry diganti dengan EmployeeListItem
- belum ada class profession, EmployeeStatus, dan Education Level
- FormalEductionHistory dan InformalEductionHistory apakah perlu dibuang 'history'nya atau nama tablenya saja yang dialter?
- FormalEducationHistory --> LastEducationID, kenapa tidak ID saja? 1 employee hanya punya 1 formalEduction
- InformalEducationHistory tidak ada ID?
- FamilyInsurance diganti Family saja
- SK dan decree(di database), baiknya pilih salah satu istilah saja.

**Comment by nadiaita** [comment]
Work -> Job
BankNumber -> BankAccountNumber
GraduationYear -> GraduateYear

**Comment by tmusthofa** [comment]
belum ada class school untuk dropdownnya?
